name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install and Build 🔧
        run: |
          npm install
          npm run build
        env:
          VITE_PROJECT_ID: ${{ secrets.VITE_PROJECT_ID }}

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # আপনার বিল্ড করা ফাইলের ডিরেক্টরি
          branch: gh-pages # এই ব্রাঞ্চে আপনার ওয়েবসাইট লাইভ হবে
